In [78]:
import numpy as np

In [79]:
img=np.load('D:new_np/PA/PA_M02_RF085.npy')

In [80]:
img=img[1,:,:]

In [81]:
img

array([[-0.12523937, -0.4975029 , -0.28623566, ..., -0.0270936 ,
        -0.09017806,  0.16057839],
       [-0.49057751, -0.50848608, -0.53803042, ..., -0.07692308,
        -0.13950617, -0.00938628],
       [-0.10385757, -0.15935057, -0.10415412, ..., -0.3677028 ,
         0.32404891, -0.1653638 ],
       ...,
       [-0.07322654, -0.49073171, -0.21409922, ...,  0.15421003,
         0.52039967, -0.41576507],
       [-0.09215798, -0.07609861, -0.32587287, ..., -0.36495084,
        -0.33538461, -0.43017726],
       [-0.23378582, -0.16683622, -0.16707258, ...,  0.04680187,
        -0.16970547, -0.32887975]])

In [68]:
img_flatten=img.flatten()

In [69]:
img_flatten

array([-0.12523937, -0.4975029 , -0.28623566, ...,  0.04680187,
       -0.16970547, -0.32887975])

In [70]:
# for i in img_flatten:
#     count=len(i[i<0.1])
#     print(count)

In [71]:
length=len(img_flatten)

In [72]:
length


1016064

In [73]:
lis=[]
for i in img_flatten:
    if i<-0.75:
        lis.append(str(i))
#print('array= ',lis)        
print('count= ',len(lis))

count=  5093


In [82]:
import numpy as np
import os
root_dir='D:new_np/'
def To_find_pixel_count(polymer,intensity_threshold):
    list=os.listdir(os.path.join(root_dir,polymer))
    img=np.load()
    img=img[1,:,:]
    img_flatten=img.flatten()
    count=0
    for i in img_flatten:
        if i<intensity_threshold:
            count=count+1
    return print(f'No of pixel intensities great than {intensity_threshold} is: ',count)
To_find_pixel_count(-0.75)

TypeError: To_find_pixel_count() missing 1 required positional argument: 'intensity_threshold'

tensor([[0.5833, 0.6033, 0.5727],
        [0.6153, 0.1173, 0.5625],
        [0.0663, 0.5105, 0.5476],
        [0.5625, 0.5505, 0.8597],
        [0.2181, 0.9214, 0.9505]])
